### ISSUE TITLE
bidirection streaming

### ISSUE THREAD

**Issue by cogmeta** [gabrielgrant/grpc-bus-websocket-proxy-client#3]
does it support bidirectional streaming?

**Comment by gabrielgrant** [comment]
Yup, that was one of the main motivations of writing this :)

For server streaming, you'll get back a `call` object that allows registering a handler for the `data` event that will be called each time a message is received: https://github.com/gabrielgrant/grpc-bus-websocket-proxy-client/blob/master/demo/demo.js#L19

For client streaming, the `call` object has a `write()` method that will send a message to the server: https://github.com/gabrielgrant/grpc-bus-websocket-proxy-client/blob/master/demo/demo.js#L23

**Comment by gabrielgrant** [comment]
Updated the README to include this info. I don't think there are any other code changes needed, so I'm going to close this, but feel free to re-open if you have issues using it

**Comment by cogmeta** [comment]
That will be awesome if it works. Let me try it out and get back to you. Thanks.

**Comment by cogmeta** [comment]
I am not able to load multi path package names com.yourname.project. It is failing at line 90 in index.js:

line 90 -    var serviceConnector = tree[protoPackageName][serviceName];

    var tree = self.tree = gbClient.buildTree();
    var packagePromises = {};
    var protoPackages = Object.keys(self.serviceMap);
    protoPackages.forEach(function(protoPackageName) {
      var servicesPromises = {};
      Object.keys(self.serviceMap[protoPackageName]).forEach(function(serviceName) {
  >>>      var serviceConnector = tree[protoPackageName][serviceName];
        var serviceAddress = self.serviceMap[protoPackageName][serviceName];
        servicesPromises[serviceName] = serviceConnector(serviceAddress);
      });
      packagePromises[protoPackageName] = RSVP.hash(servicesPromises)
    })
    var promiseHash = RSVP.hash(packagePromises)
    return promiseHash;
  }).then(function(results) {
    self.services = results;
    return self;
  });

**Comment by gabrielgrant** [comment]
Sorry, I'm having trouble following this. Can you please clarify what it is that you're trying to do, what it is you're expecting to happen, and what the error is that you're seeing?

(if you're reporting an issue directly related to bidi streaming, please re-open this issue, or if it's not directly related, please open as a new issue. and either way, please wrap multi-line blocks of code in ` ``` ` to have them be formatted properly)
