### ISSUE TITLE
can not load *.proto.json file

### ISSUE THREAD

**Issue by cogmeta** [gabrielgrant/grpc-bus-websocket-proxy-client#4]
The demo example does not with hellworld.proto.json file created using pbjs and the instructions given?  it works with hellworld.proto but not with hellworld.proto.json. how to load hellworld.proto.json?
Just replacing hellworld.proto with hellworld.proto.json does not work.

**Comment by cogmeta** [comment]
I have a more complex proto defs that import other .proto files so single proto is not possible. I created proto.json but dont know how to load

**Comment by gabrielgrant** [comment]
yes, as mentioned in the readme, i believe the only way to use a proto file with other protos imported in protobufjs is to compile it with `pbjs` (this is what we do for the fairly-complex and interdependent [pachyderm protobuf definitions](https://github.com/pachyderm/pachyderm/blob/master/src/client/pps/pps.proto) ). Once you have the compiled/jsonified proto tree, you should be able to just pass the path to that JSON file when creating the client. Example from the pachyderm dashboard:

```
new GBC(proxyUrl, '/proto/pps.proto.json', {pps: {API: pachdUrl}})
      .connect()
      .then(gbc => {
        console.log('PPS API connected');
        ...
```

Are you saying that loading a compiled proto isn't working for you? What's the error you're seeing?

**Comment by cogmeta** [comment]
index.js:17 Assertion failed: TypeError: Cannot read property 'Greeter' of undefined
    at index.js:90
    at Array.forEach (<anonymous>)
    at index.js:89
    at Array.forEach (<anonymous>)
    at index.js:87
    at tryCatch (rsvp.es.js:519)
    at invokeCallback (rsvp.es.js:532)
    at publish (rsvp.es.js:502)
    at MutationObserver.flush (rsvp.es.js:2409)
(anonymous) @ index.js:17
trigger @ rsvp.es.js:193
(anonymous) @ rsvp.es.js:1042
setTimeout (async)
./node_modules/@cogmeta/web-speech-client/node_modules/rsvp/dist/rsvp.es.js.config.after @ rsvp.es.js:2463
_onError @ rsvp.es.js:1040
publishRejection @ rsvp.es.js:434
flush @ rsvp.es.js:2409
characterData (async)
(anonymous) @ rsvp.es.js:2383
asap @ rsvp.es.js:2340
fulfill @ rsvp.es.js:453
handleMaybeThenable @ rsvp.es.js:418
resolve @ rsvp.es.js:426
(anonymous) @ rsvp.es.js:566
ws.onopen @ index.js:48



  var servicesPromises = {};
      Object.keys(self.serviceMap[protoPackageName]).forEach(function(serviceName) {
        var serviceConnector = tree[protoPackageName][serviceName];
        var serviceAddress = self.serviceMap[protoPackageName][serviceName];
        servicesPromises[serviceName] = serviceConnector(serviceAddress);
      });

**Comment by cogmeta** [comment]
index.js:90  var serviceConnector = tree[protoPackageName][serviceName];

**Comment by cogmeta** [comment]
It is not able to build the tree [tree is empty, {}] when helloworld.proto.json is supplied but woks fine with helloworld.proto

**Comment by gabrielgrant** [comment]
Hrm...that's strange. Can you please show me the full code you're using to initialize this that is causing the error to occur? (preferably wrapped in ` ``` ` so it is properly formatted :) )

**Comment by cogmeta** [comment]
Does it expect package name to be simple like "helloword" and not multi-level like "com.yourname.project"?

**Comment by cogmeta** [comment]
I can now load "helloworld.proto.json but my own *.proto.json. The package name is multi-level in my proto.json. Is that causing any issues?

**Comment by cogmeta** [comment]
got bidirectional streaming working in grpc-web over websocket. Dont need this anymore. Thanks for your time.

**Comment by gabrielgrant** [comment]
@cogmeta Oh, interesting -- my understanding was that grpc-web only supported streaming from the server, not from the client?

Also, if you're able to provide any more details on what the problem was, it would be useful to improve the docs to save others from wasting their time

Thanks

**Comment by gabrielgrant** [comment]
Indeed, the grpc-web readme explicitly says they don't support client-side streaming: https://github.com/improbable-eng/grpc-web#client-side-streaming

So I'd be quite curious to know how you got it working?

**Comment by cogmeta** [comment]
It does now. you can have bidirectional steaming with grpc web proxy and it works like a harm.  Take a look at https://github.com/improbable-eng/grpc-web/issues/205 and https://github.com/improbable-eng/grpc-web/issues/210

**Comment by gabrielgrant** [comment]
Interesting. Good to know, thanks!
